workflows:
  ios-workflow:
    name: JumpingChickenIos
    # ....
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.ctkgames.jumpingchicken
